/*
Floating Roses Animation (GSAP v1)
Stops after 2 minutes
*/

TweenLite.set("#container", { perspective: 600 });
TweenLite.set("img", { xPercent: "-50%", yPercent: "-50%" });

var total = 30;
var warp = document.getElementById("container"),
    w = window.innerWidth,
    h = window.innerHeight;

var dots = [];

// Create dots
for (let i = 0; i < total; i++) { 
  var Div = document.createElement('div');
  
  TweenLite.set(Div, {
    attr: { class: 'dot' },
    x: R(0, w),
    y: R(-200, -150),
    z: R(-200, 200)
  });
  
  warp.appendChild(Div);
  dots.push(Div);
  animm(Div);
}

// Animation function
function animm(elm) {   
  TweenMax.to(elm, R(6, 15), {
    y: h + 100,
    ease: Linear.easeNone,
    repeat: -1,
    delay: -15
  });

  TweenMax.to(elm, R(4, 8), {
    x: '+=100',
    rotationZ: R(0, 180),
    repeat: -1,
    yoyo: true,
    ease: Sine.easeInOut
  });

  TweenMax.to(elm, R(2, 8), {
    rotationX: R(0, 360),
    rotationY: R(0, 360),
    repeat: -1,
    yoyo: true,
    ease: Sine.easeInOut,
    delay: -5
  });
}

// Random function
function R(min, max) {
  return min + Math.random() * (max - min);
}

setTimeout(function () {
  dots.forEach(dot => {
    TweenMax.to(dot, 1, { opacity: 0, onComplete: () => dot.remove() });
  });
}, 12000);


const data = [
    { lang: "Tamil", word: "அம்மா" },
    { lang: "Hindi", word: "माँ" },
    { lang: "Telugu", word: "అమ్మ" },

    { lang: "Aari (Omotic)", word: "Amma" },
    { lang: "Abanyom (Bantu)", word: "Amma" },
    { lang: "Abujmaria (Dravidian)", word: "Amma" },
    { lang: "Adele (Kwa)", word: "Amma" },
    { lang: "Afar (Cushitic)", word: "ina" },
    { lang: "Afrikaans (Germanic)", word: "ma" },
    { lang: "Aini (Turkic)", word: "ana" },
    { lang: "Ainu (Isolate)", word: "Amma" },
    { lang: "Akan (Kwa)", word: "ɛna" },
    { lang: "Akawaio (Carib)", word: "Amma" },
    { lang: "Albanian (Indo-European)", word: "nënë" },
    { lang: "Aleut (Eskimo–Aleut)", word: "ama" },
    { lang: "Algonquin (Algonquian)", word: "Amma" },
    { lang: "Alsatian (Germanic)", word: "màmm" },
    { lang: "Altay (Turkic)", word: "ene" },
    { lang: "Amdang (Nilo-Saharan)", word: "Amma" },
    { lang: "Amharic (Semitic)", word: "እናት" },
    { lang: "Anda (Khoisan)", word: "Amma" },
    { lang: "Angika (Indo-Aryan)", word: "अम्मा" },
    { lang: "Anyin (Kwa)", word: "Amma" },
    { lang: "Ao (Tibeto-Burman)", word: "Amma" },
    { lang: "A-Pucikwar (Andamanese)", word: "Amma" },
    { lang: "Arabic (Semitic)", word: "أم" },
    { lang: "Aragonese (Romance)", word: "madre" },
    { lang: "Aramaic (Semitic)", word: "ܐܡܐ" },
    { lang: "Are (Malayo-Polynesian)", word: "Amma" },
    { lang: "Argobba (Semitic)", word: "Amma" },
    { lang: "Armenian (Indo-European)", word: "մայր" },
    { lang: "Arvanitic (Indo-European)", word: "nënë" },
    { lang: "Ashkun (Indo-Iranian)", word: "Amma" },
    { lang: "Asi (Malayo-Polynesian)", word: "Amma" },
    { lang: "Assamese (Indo-Iranian)", word: "আই" },
    { lang: "Asturian (Romance)", word: "madre" },
    { lang: "Ateso / Teso (Nilotic)", word: "Amma" },
    { lang: "A’Tong (Tibeto-Burman)", word: "Amma" },
    { lang: "Auslan (Sign Language)", word: "🤟 (mother sign)" },
    { lang: "Avestan (Indo-Iranian)", word: "Amma" },
    { lang: "Awadhi (Indo-Iranian)", word: "अम्मा" },
    { lang: "Aymara (Aymaran)", word: "tayka" },
    { lang: "Azerbaijani (Turkic)", word: "ana" },

    { lang: "Badaga (Dravidian)", word: "ಅಮ್ಮ / Amma" },
    { lang: "Badeshi (Indo-Iranian)", word: "Amma" },
    { lang: "Bahnar (Austroasiatic)", word: "mâ" },
    { lang: "Balochi (Indo-Iranian)", word: "mā" },
    { lang: "Balti (Tibeto-Burman)", word: "ama" },
    { lang: "Bartangi (Iranian)", word: "mā" },
    { lang: "Basaa (Bantu)", word: "nyaŋ" },
    { lang: "Bashkardi (Iranian)", word: "Amma" },
    { lang: "Bashkir (Turkic)", word: "әсәй (äsäy)" },
    { lang: "Basque (Isolate)", word: "ama" },
    { lang: "Bats (North Caucasian)", word: "Amma" },
    { lang: "Beja (Cushitic)", word: "ina" },
    { lang: "Belarusian (Slavic)", word: "маці (matsi)" },
    { lang: "Belhare (Tibeto-Burman)", word: "ama" },
    { lang: "Bemba (Bantu)", word: "banina" },
    { lang: "Bengali", word: "মা (ma)" },
    { lang: "Berta (Nilo-Saharan)", word: "Amma" },
    { lang: "Bete (Niger–Congo)", word: "Amma" },
    { lang: "Bhili (Indo-Aryan)", word: "माँ" },
    { lang: "Bhojpuri (Indo-Aryan)", word: "माई (mai)" },
    { lang: "Bikol (Malayo-Polynesian)", word: "ina" },
    { lang: "Bikya / Furu (Bantu)", word: "Amma" },
    { lang: "Bissa (Mande)", word: "Amma" },
    { lang: "Blackfoot (Algonquian)", word: "Amma" },
    { lang: "Bodo", word: "आइ (ai)" },
    { lang: "Bonan / Paoan (Mongolic)", word: "ama" },
    { lang: "Bororo (Bororoan)", word: "Amma" },
    { lang: "Bosnian (Slavic)", word: "majka" },
    { lang: "Brahui (Dravidian)", word: "amma" },
    { lang: "Breton (Celtic)", word: "mamm" },
    { lang: "Bua (Niger–Congo)", word: "Amma" },
    { lang: "Bukusu (Bantu)", word: "mama" },
    { lang: "Bulgarian (Slavic)", word: "майка (mayka)" },
    { lang: "Bunjevac (Slavic)", word: "majka" },
    { lang: "Burmese (Tibeto-Burman)", word: "အမေ (ame)" },
    { lang: "Buryat (Mongolic)", word: "эхэ (ekhe)" },


    { lang: "Caddo (Caddoan)", word: "Amma" },
    { lang: "Cahuilla (Uto-Aztecan)", word: "Amma" },
    { lang: "Cantonese (Sinitic)", word: "媽媽 (maa1 maa1)" },
    { lang: "Catalan (Romance)", word: "mare" },
    { lang: "Cayuga (Iroquoian)", word: "Amma" },
    { lang: "Chaga / Kichagga (Bantu)", word: "mama" },
    { lang: "Chakma (Indo-Aryan)", word: "মা (ma)" },
    { lang: "Chenchu (Dravidian)", word: "amma" },
    { lang: "Chenoua (Berber)", word: "yemma" },
    { lang: "Cherokee (Iroquoian)", word: "Etsi" },
    { lang: "Cheyenne (Algonquian)", word: "ehestse" },
    { lang: "Chickasaw (Muskogean)", word: "Amma" },
    { lang: "Chilcotin (Athabaskan)", word: "Amma" },
    { lang: "Chinese (Sinitic)", word: "妈妈 (māma)" },
    { lang: "Chipewyan (Athabaskan)", word: "Amma" },
    { lang: "Chittagonian (Indo-Aryan)", word: "ma" },
    { lang: "Choctaw (Muskogean)", word: "Amma" },
    { lang: "Chulym (Turkic)", word: "ana" },
    { lang: "Church Slavonic (Slavic)", word: "мати (mati)" },
    { lang: "Chuvash (Turkic)", word: "анне (anne)" },
    { lang: "Cocoma / Cocama (Tupian)", word: "Amma" },
    { lang: "Cocopa (Hokan)", word: "Amma" },
    { lang: "Coeur d’Alene (Salishan)", word: "Amma" },
    { lang: "Comanche (Uto-Aztecan)", word: "Amma" },
    { lang: "Comorian (Bantu)", word: "mama" },
    { lang: "Corsican (Romance)", word: "mamma" },
    { lang: "Cree (Algonquian)", word: "nimâmâ" },
    { lang: "Croatian (Slavic)", word: "majka" },
    { lang: "Czech (Slavic)", word: "matka" },

    { lang: "Dagbani (Gur)", word: "naa" },
    { lang: "Dahlik (Semitic)", word: "umm" },
    { lang: "Dalecarlian (Germanic)", word: "mora" },
    { lang: "Dameli (Indo-Aryan)", word: "ama" },
    { lang: "Danish (Germanic)", word: "mor" },
    { lang: "Dari-Persian (Iranian)", word: "مادر (mādar)" },
    { lang: "Daur / Dagur (Mongolic)", word: "eje" },
    { lang: "Dhatki (Indo-Aryan)", word: "maa" },
    { lang: "Dida (Kru)", word: "Amma" },
    { lang: "Dioula / Jula (Mande)", word: "ba" },
    { lang: "Dogri (Indo-Aryan)", word: "माँ (mā̃)" },
    { lang: "Dolgan (Turkic)", word: "iye" },
    { lang: "Duala (Bantu)", word: "mama" },
    { lang: "Dungan (Sinitic)", word: "妈妈 (mama)" },
    { lang: "Dutch (Germanic)", word: "moeder" },
    { lang: "Dzongkha (Tibeto-Burman)", word: "ཨ་མ (ama)" },

    { lang: "Eastern Yugur (Mongolic)", word: "ama" },
    { lang: "Edo (Nigeria)", word: "mama" },
    { lang: "Efik (Nigeria)", word: "ñkɔ" },
    { lang: "Egyptian Arabic (Semitic)", word: "mama" },
    { lang: "Ekoti (Bantu)", word: "mama" },
    { lang: "English (Germanic)", word: "mother" },
    { lang: "Erzya (Uralic)", word: "ava" },
    { lang: "Esan (Nigeria)", word: "mama" },
    { lang: "Estonian (Uralic)", word: "ema" },
    { lang: "Even (Tungusic)", word: "eme" },
    { lang: "Ewe (Volta–Niger)", word: "da" },
    { lang: "Extremaduran (Romance)", word: "madri" },

    { lang: "Fang (Bantu)", word: "mama" },
    { lang: "Finnish (Uralic)", word: "äiti" },
    { lang: "Fon (Volta–Niger)", word: "nyɔ" },
    { lang: "French (Romance)", word: "mère" },
    { lang: "Frisian, North (Germanic)", word: "mem" },
    { lang: "Frisian, West (Germanic)", word: "mem" },
    { lang: "Friulian (Romance)", word: "mare" },
    { lang: "Fur (Nilo-Saharan)", word: "Amma" },

    { lang: "Ga (Kwa)", word: "ena" },
    { lang: "Gadaba (Dravidian)", word: "amma" },
    { lang: "Gagauz (Turkic)", word: "ana" },
    { lang: "Galician (Romance)", word: "nai" },
    { lang: "Gallo (Romance)", word: "maer" },
    { lang: "Gan (Sinitic)", word: "妈妈 (māma)" },
    { lang: "Ganda (Bantu)", word: "nnyina" },
    { lang: "Gangte (Tibeto-Burman)", word: "ama" },
    { lang: "Garhwali (Indo-Aryan)", word: "ma" },
    { lang: "Gayo (Malayo-Polynesian)", word: "ine" },
    { lang: "German (Germanic)", word: "Mutter" },
    { lang: "Gikuyu / Kikuyu (Bantu)", word: "mama" },
    { lang: "Gileki (Iranian)", word: "mādar" },
    { lang: "Goaria (Indo-Aryan)", word: "ma" },
    { lang: "Gondi (Dravidian)", word: "amma" },
    { lang: "Gowro (Indo-Aryan)", word: "ama" },
    { lang: "Greek (Indo-European)", word: "μητέρα (mitéra)" },
    { lang: "Guaraní (Tupian)", word: "sy" },
    { lang: "Gujarati (Indo-Aryan)", word: "મા (mā)" },
    { lang: "Gusii (Bantu)", word: "mama" },
    { lang: "Gwichʼin (Athabaskan)", word: "Amma" },

    // H languages
    { lang: "Hadza (Isolate)", word: "Amma" },
    { lang: "Haida (Na-Dené)", word: "Amma" },
    { lang: "Hakka (Sinitic)", word: "阿媽 (â-mà)" },
    { lang: "Hän (Athabaskan)", word: "Amma" },
    { lang: "Harari (Semitic)", word: "inno" },
    { lang: "Harauti (Indo-Aryan)", word: "maa" },
    { lang: "Harsusi (Semitic)", word: "umm" },
    { lang: "Harzani (Iranian)", word: "mādar" },
    { lang: "Hausa (Afro-Asiatic)", word: "uwa" },
    { lang: "Hebrew (Semitic)", word: "אֵם (em)" },
    { lang: "Herero (Bantu)", word: "mama" },
    { lang: "Hértevin (Semitic)", word: "emma" },
    { lang: "Hixkaryana (Carib)", word: "Amma" },
    { lang: "Hmong (Hmong–Mien)", word: "niam" },
    { lang: "Ho (Austroasiatic)", word: "Amma" },
    { lang: "Hobyót (Semitic)", word: "umm" },
    { lang: "Hopi (Uto-Aztecan)", word: "Amma" },
    { lang: "Hulaulá (Semitic)", word: "em" },
    { lang: "Hungarian (Uralic)", word: "anya" },
    { lang: "Hunsrik (Brazil)", word: "mutter" },

    // I languages
    { lang: "Iban (Malayo-Polynesian)", word: "emai" },
    { lang: "Ibibio (Benue–Congo)", word: "màmá" },
    { lang: "Icelandic (Germanic)", word: "móðir" },
    { lang: "Ifè (Volta–Congo)", word: "iya" },
    { lang: "Ili Turki (Turkic)", word: "ana" },
    { lang: "Inari Sami (Uralic)", word: "eäni" },
    { lang: "Inuktitut (Eskimo–Aleut)", word: "aania" },
    { lang: "Inupiaq (Eskimo–Aleut)", word: "aaniq" },
    { lang: "Iraqw (Cushitic)", word: "ayda" },
    { lang: "Irula (Dravidian)", word: "amma" },
    { lang: "Istro-Romanian (Romance)", word: "mama" },
    { lang: "Italian (Romance)", word: "mamma" },

    // J languages
    { lang: "Japanese (Japonic)", word: "母 (haha)" },
    { lang: "Jaqaru (Aymaran)", word: "Amma" },
    { lang: "Jarai (Malayo-Polynesian)", word: "mẹ" },
    { lang: "Juang (Austroasiatic)", word: "Amma" },
    { lang: "Jurchen (Tungusic)", word: "Amma" },

    // K languages
    { lang: "Kabyle (Berber)", word: "yemma" },
    { lang: "Kalasha (Indo-Aryan)", word: "ama" },
    { lang: "Kannada (Dravidian)", word: "ಅಮ್ಮ (amma)" },
    { lang: "Karachay-Balkar (Turkic)", word: "ana" },
    { lang: "Karagas (Turkic)", word: "ene" },
    { lang: "Karaim (Turkic)", word: "ana" },
    { lang: "Karakalpak (Turkic)", word: "ana" },
    { lang: "Karelian (Uralic)", word: "ema" },
    { lang: "Kashmiri (Indo-Aryan)", word: "माँ (maa)" },
    { lang: "Kashubian (Slavic)", word: "mòwa" },
    { lang: "Kazakh (Turkic)", word: "ана (ana)" },
    { lang: "Kerek (Paleosiberian)", word: "Amma" },
    { lang: "Ket (Chukotko-Kamchatkan)", word: "Amma" },
    { lang: "Khakas (Turkic)", word: "ine" },
    { lang: "Khalaj (Turkic)", word: "ana" },
    { lang: "Khandeshi (Indo-Aryan)", word: "ma" },
    { lang: "Khanty (Uralic)", word: "emi" },
    { lang: "Khasi (Austroasiatic)", word: "mei" },
    { lang: "Khitan (Mongolic)", word: "Amma" },
    { lang: "Khmer (Austroasiatic)", word: "ម៉ែ (mae)" },
    { lang: "Khmu (Austroasiatic)", word: "me" },
    { lang: "Khowar (Indo-Aryan)", word: "ama" },
    { lang: "Kildin Sami (Uralic)", word: "eeme" },
    { lang: "Kimatuumbi (Bantu)", word: "mama" },
    { lang: "Kinyarwanda (Bantu)", word: "mama" },
    { lang: "Kirombo (Bantu)", word: "mama" },
    { lang: "Kirundi (Bantu)", word: "mama" },
    { lang: "Kivunjo (Bantu)", word: "mama" },
    { lang: "Kolami (Dravidian)", word: "amma" },
    { lang: "Kongo / Kikongo (Bantu)", word: "mama" },
    { lang: "Konkani (Indo-Aryan)", word: "आई (ai)" },
    { lang: "Koraga (Dravidian)", word: "amma" },
    { lang: "Korandje (Nilo-Saharan)", word: "Amma" },
    { lang: "Korean (Isolate)", word: "어머니 (eomeoni)" },
    { lang: "Korku (Austroasiatic)", word: "Amma" },
    { lang: "Korwa (Austroasiatic)", word: "Amma" },
    { lang: "Kota (Dravidian)", word: "amma" },
    { lang: "Koya (Dravidian)", word: "amma" },
    { lang: "Kui (Dravidian)", word: "amma" },
    { lang: "Kumauni (Indo-Aryan)", word: "ma" },
    { lang: "Kumyk (Turkic)", word: "ana" },
    { lang: "Kumzari (Iranian)", word: "mādar" },
    { lang: "Kurdish (Iranian)", word: "دایک (dayik)" },
    { lang: "Kusunda (Isolate)", word: "Amma" },
    { lang: "Kxoe (Khoisan)", word: "Amma" },

    { lang: "Laal (Unclassified)", word: "Amma" },
    { lang: "Ladakhi (Tibeto-Burman)", word: "ama" },
    { lang: "Ladin (Romance)", word: "mare" },
    { lang: "Laki (Iranian)", word: "mādar" },
    { lang: "Larestani (Iranian)", word: "mā" },
    { lang: "Latvian (Baltic)", word: "māte" },
    { lang: "Leonese (Romance)", word: "ma" },
    { lang: "Lepcha (Indo-Aryan)", word: "ama" },
    { lang: "Ligbi (Mande)", word: "ba" },
    { lang: "Limbu (Indo-Aryan)", word: "aama" },
    { lang: "Limburgish (Germanic)", word: "moeër" },
    { lang: "Lingala (Bantu)", word: "mama" },
    { lang: "Lipan Apache (Athabaskan)", word: "Amma" },
    { lang: "Lishana Deni (Semitic)", word: "em" },
    { lang: "Lithuanian (Baltic)", word: "motina" },
    { lang: "Livonian (Uralic)", word: "ema" },
    { lang: "Lombard (Romance)", word: "mader" },
    { lang: "Lotha (Tibeto-Burman)", word: "ama" },
    { lang: "Lower Sorbian (Slavic)", word: "mać" },
    { lang: "Lozi (Bantu)", word: "ma" },
    { lang: "Ludic (Uralic)", word: "emä" },
    { lang: "Lunda (Bantu)", word: "mama" },
    { lang: "Luo (Nilotic)", word: "miyo" },
    { lang: "Luri (Iranian)", word: "mādar" },
    { lang: "Lushootseed (Salishan)", word: "Amma" },
    { lang: "Lusoga (Bantu)", word: "maama" },
    { lang: "Luvale (Bantu)", word: "mama" },
    { lang: "Luwati (Indo-Iranian)", word: "mā" },
    { lang: "Luxembourgish (Germanic)", word: "mamm" },
    { lang: "Lycian (Indo-European)", word: "Amma" },
    { lang: "Lydian (Indo-European)", word: "Amma" },

    // M languages
    { lang: "Macedonian (Slavic)", word: "мајка (majka)" },
    { lang: "Magadhi (Indo-Aryan)", word: "ma" },
    { lang: "Maithili (Indo-Aryan)", word: "माँ (maa)" },
    { lang: "Makhuwa (Bantu)", word: "mama" },
    { lang: "Makhuwa-Meetto (Bantu)", word: "mama" },
    { lang: "Malay (Malayo-Polynesian)", word: "ibu" },
    { lang: "Malayalam (Dravidian)", word: "അമ്മ (amma)" },
    { lang: "Maltese (Semitic)", word: "omm" },
    { lang: "Mam (Mayan)", word: "na" },
    { lang: "Manchu (Tungusic)", word: "ama" },
    { lang: "Mandaic (Semitic)", word: "em" },
    { lang: "Mandarin (Sinitic)", word: "妈妈 (māma)" },
    { lang: "Mandinka (Mande)", word: "ba" },
    { lang: "Mansi (Uralic)", word: "oma" },
    { lang: "Manx (Celtic)", word: "mannin" },
    { lang: "Manyika (Bantu)", word: "mama" },
    { lang: "Maori (Malayo-Polynesian)", word: "whaea" },
    { lang: "Marathi (Indo-Aryan)", word: "आई (ai)" },
    { lang: "Mari (Uralic)", word: "ava" },
    { lang: "Maria (Dravidian)", word: "amma" },
    { lang: "Masaba (Bantu)", word: "mama" },
    { lang: "Maya (Mayan)", word: "na" },
    { lang: "Mehri (Semitic)", word: "em" },
    { lang: "Menominee (Algonquian)", word: "Amma" },
    { lang: "Meru (Bantu)", word: "muru" },
    { lang: "Mirandese (Romance)", word: "mai" },
    { lang: "Moghol (Mongolic)", word: "Amma" },
    { lang: "Mohawk (Iroquoian)", word: "Amma" },
    { lang: "Moksha (Uralic)", word: "ava" },
    { lang: "Molengue (Bantu)", word: "mama" },
    { lang: "Mon (Austroasiatic)", word: "mei" },
    { lang: "Mongolian (Mongolic)", word: "ээж (eej)" },
    { lang: "Mono (Malayo-Polynesian)", word: "ina" },
    { lang: "Mono (Ubangian)", word: "Amma" },
    { lang: "Mono (Uto-Aztecan)", word: "Amma" },
    { lang: "Montagnais (Algonquian)", word: "nukum" },
    { lang: "Montenegrin (Slavic)", word: "majka" },
    { lang: "Motu (Malayo-Polynesian)", word: "sinana" },
    { lang: "Muher (Semitic)", word: "em" },
    { lang: "Mundari (Austroasiatic)", word: "aama" },
    { lang: "Munji (Iranian)", word: "mādar" },
    { lang: "Muria (Dravidian)", word: "amma" },

    // N languages
    { lang: "Nǀu (Khoisan)", word: "Amma" },
    { lang: "Nafaanra (Senufo)", word: "Amma" },
    { lang: "Nagarchal (Dravidian)", word: "amma" },
    { lang: "Nahuatl (Uto-Aztecan)", word: "nan" },
    { lang: "Nama (Khoisan)", word: "Amma" },
    { lang: "Nanai (Tungusic)", word: "ama" },
    { lang: "Ndebele (Bantu)", word: "umama" },
    { lang: "Ndonga (Bantu)", word: "meme" },
    { lang: "Neapolitan (Romance)", word: "mammà" },
    { lang: "Negidal (Tungusic)", word: "ama" },
    { lang: "Nepali (Indo-Aryan)", word: "आमा (ama)" },
    { lang: "Ngumba (Bantu)", word: "mama" },
    { lang: "Nias", word: "ina" },
    { lang: "Niellim (Adamawa)", word: "Amma" },
    { lang: "Nogai (Turkic)", word: "ana" },
    { lang: "Northern Sami (Uralic)", word: "eadni" },
    { lang: "Nuer (Nilotic)", word: "naan" },
    { lang: "Nyabwa (Kru)", word: "Amma" },
    { lang: "Nyah Kur (Austroasiatic)", word: "ame" },
    { lang: "Nyoro (Bantu)", word: "maama" },

    // O languages
    { lang: "Odia (Indo-Aryan)", word: "ମା (ma)" },
    { lang: "Okinawan (Japonic)", word: "アンマー (anmā)" },
    { lang: "Omagua (Tupian)", word: "Amma" },
    { lang: "Ongota (Afro-Asiatic)", word: "Amma" },
    { lang: "Ormuri (Iranian)", word: "mādar" },
    { lang: "Oroch (Tungusic)", word: "ama" },
    { lang: "Orok (Tungusic)", word: "ama" },

    // P languages
    { lang: "Parachi (Iranian)", word: "mādar" },
    { lang: "Parya (Indo-Aryan)", word: "ama" },
    { lang: "Phalura (Indo-Aryan)", word: "ama" },
    { lang: "Phuthi (Bantu)", word: "mama" },
    { lang: "Picard (Romance)", word: "mère" },
    { lang: "Pig Latin", word: "Amma" },
    { lang: "Pirahã (Mura)", word: "xíi" },
    { lang: "Polish (Slavic)", word: "matka" },
    { lang: "Portuguese (Romance)", word: "mãe" },
    { lang: "Puelche (Isolate)", word: "Amma" },
    { lang: "Puma (Tibeto-Burman)", word: "ama" },

    // Q languages
    { lang: "Quechua (Peru)", word: "mama" },

    // R languages
    { lang: "Rajasthani (Indo-Aryan)", word: "maa" },
    { lang: "Romanian (Romance)", word: "mamă" },
    { lang: "Romany (Indo-Iranian)", word: "daj" },
    { lang: "Rotokas (East Papuan)", word: "Amma" },
    { lang: "Russian (Slavic)", word: "мать (matʹ)" },

    // S languages
    { lang: "Sadri (Indo-Aryan)", word: "ma" },
    { lang: "Salar (Turkic)", word: "ana" },
    { lang: "Sandawe (Khoisan)", word: "Amma" },
    { lang: "Santali (Austroasiatic)", word: "aama" },
    { lang: "Sara (Malayo-Polynesian)", word: "ina" },
    { lang: "Sardinian (Romance)", word: "mamma" },
    { lang: "Sarikoli (Iranian)", word: "mādar" },
    { lang: "Savara (Dravidian)", word: "amma" },
    { lang: "Savi (Indo-Aryan)", word: "ma" },
    { lang: "Sawai (Malayo-Polynesian)", word: "ina" },
    { lang: "Semnani (Iranian)", word: "mādar" },
    { lang: "Senaya (Semitic)", word: "em" },
    { lang: "Serbian (Slavic)", word: "мајка (majka)" },
    { lang: "Serbo-Croatian (Slavic)", word: "majka" },
    { lang: "Sesotho (Bantu)", word: "mme" },
    { lang: "Seto / Setu (Uralic)", word: "ema" },
    { lang: "Shimaore (Bantu)", word: "mama" },
    { lang: "Shina (Indo-Aryan)", word: "ama" },
    { lang: "Shona (Bantu)", word: "mai" },
    { lang: "Shor (Turkic)", word: "ene" },
    { lang: "Shoshoni (Uto-Aztecan)", word: "Amma" },
    { lang: "Shughni (Iranian)", word: "mādar" },
    { lang: "Shumashti (Indo-Aryan)", word: "ama" },
    { lang: "Shuswap (Salishan)", word: "Amma" },
    { lang: "Sicilian (Romance)", word: "mamma" },
    { lang: "Sidamo (Cushitic)", word: "ayye" },
    { lang: "Sika (Malayo-Polynesian)", word: "ina" },
    { lang: "Silesian (Slavic)", word: "moma" },
    { lang: "Sindhi (Indo-Aryan)", word: "maa" },
    { lang: "Sinhalese (Indo-Aryan)", word: "අම්මා (amma)" },
    { lang: "Sioux (Siouan)", word: "Amma" },
    { lang: "Sivandi (Iranian)", word: "mādar" },
    { lang: "Skolt Sami (Uralic)", word: "ääʹnn" },
    { lang: "Slavey (Athabaskan)", word: "Amma" },
    { lang: "Slovak (Slavic)", word: "matka" },
    { lang: "Somali (Cushitic)", word: "hooyo" },
    { lang: "Sonjo / Temi (Bantu)", word: "mama" },
    { lang: "Soqotri (Semitic)", word: "em" },
    { lang: "Sora (Austroasiatic)", word: "ama" },
    { lang: "Sorbian, Lower (Slavic)", word: "mać" },
    { lang: "Sorbian, Upper (Slavic)", word: "mać" },
    { lang: "Sourashtra (Indo-Aryan)", word: "maa" },
    { lang: "South Estonian (Uralic)", word: "ema" },
    { lang: "Southern Sami (Uralic)", word: "aahka" },
    { lang: "Spanish (Romance)", word: "madre" },
    { lang: "Standard Arabic", word: "أم (umm)" },
    { lang: "Suba (Bantu)", word: "mama" },
    { lang: "Susu (Mande)", word: "ba" },
    { lang: "Svan (South Caucasian)", word: "deda" },
    { lang: "Swahili (Bantu)", word: "mama" },
    { lang: "Swedish (Germanic)", word: "mor" },
    { lang: "Syriac (Semitic)", word: "ܐܡܐ (emma)" },

    // T languages
    { lang: "Tachelhit (Berber)", word: "yemma" },
    { lang: "Tajik (Iranian)", word: "modar" },
    { lang: "Takestani (Iranian)", word: "mādar" },
    { lang: "Talysh (Iranian)", word: "mā" },
    { lang: "Tamil (Dravidian)", word: "அம்மா (amma)" },
    { lang: "Tanacross (Athabaskan)", word: "Amma" },
    { lang: "Tangut (Tibeto-Burman)", word: "Amma" },
    { lang: "Tat / Tati (Iranian)", word: "mādar" },
    { lang: "Tatar (Turkic)", word: "әни (äni)" },
    { lang: "Tehuelche (Chon)", word: "Amma" },
    { lang: "Telugu (Dravidian)", word: "అమ్మ (amma)" },
    { lang: "Tetum (Malayo-Polynesian)", word: "inan" },
    { lang: "Thai (Tai–Kadai)", word: "แม่ (mæ̂)" },
    { lang: "Tharu (Indo-Aryan)", word: "ma" },
    { lang: "Tibetan (Tibeto-Burman)", word: "ཨ་མ (ama)" },
    { lang: "Tigre (Semitic)", word: "em" },
    { lang: "Tigrinya (Semitic)", word: "እናት (enat)" },
    { lang: "Tiv (Benue–Congo)", word: "mama" },
    { lang: "Tlingit (Na-Dené)", word: "Amma" },
    { lang: "Toda (Dravidian)", word: "amma" },
    { lang: "Tonga (Bantu)", word: "mama" },
    { lang: "Tregami (Indo-Aryan)", word: "ama" },
    { lang: "Tsat (Malayo-Polynesian)", word: "ina" },
    { lang: "Tsonga (Bantu)", word: "mama" },
    { lang: "Tu / Monguor (Mongolic)", word: "eje" },
    { lang: "Tulu (Dravidian)", word: "amma" },
    { lang: "Tumbuka (Bantu)", word: "mayi" },
    { lang: "Tupiniquim (Tupian)", word: "Amma" },
    { lang: "Turkish (Turkic)", word: "anne" },
    { lang: "Turkmen (Turkic)", word: "ene" },
    { lang: "Turoyo (Semitic)", word: "em" },

 // U languages
    { lang: "Udmurt (Uralic)", word: "мама (mama)" },
    { lang: "Ukrainian (Slavic)", word: "мати (maty)" },
    { lang: "Ulch (Tungusic)", word: "ama" },
    { lang: "Upper Sorbian (Slavic)", word: "mać" },
    { lang: "Urdu (Indo-Aryan)", word: "ماں (maa)" },
    { lang: "Urum (Turkic)", word: "ana" },
    { lang: "Ute (Uto-Aztecan)", word: "Amma" },
    { lang: "Uyghur (Turkic)", word: "ana" },
    { lang: "Uzbek (Turkic)", word: "ona" },

    // V languages
    { lang: "Vafsi (Iranian)", word: "mādar" },
    { lang: "Valencian (Romance)", word: "mare" },
    { lang: "Venetian (Romance)", word: "mama" },
    { lang: "Veps (Uralic)", word: "ema" },
    { lang: "Võro (Uralic)", word: "ema" },
    { lang: "Votic (Uralic)", word: "emä" },

    // W languages
    { lang: "Waddar (Dravidian)", word: "amma" },
    { lang: "Wakhi (Iranian)", word: "mādar" },
    { lang: "Walloon (Romance)", word: "mame" },
    { lang: "Washo (Hokan)", word: "Amma" },
    { lang: "Welsh (Celtic)", word: "mam" },
    { lang: "Wolane (Semitic)", word: "em" },
    { lang: "Wolof (Niger–Congo)", word: "yaay" },
    { lang: "Wu (Sinitic)", word: "媽媽 (māma)" },

    // X languages
    { lang: "Xhosa (Bantu)", word: "mama" },
    { lang: "Xiang (Sinitic)", word: "妈妈 (māma)" },
    { lang: "Xibe (Tungusic)", word: "ama" },
    { lang: "Xipaya (Tupian)", word: "Amma" },

    // Y languages
    { lang: "Yaaku", word: "Amma" },
    { lang: "Yaeyama", word: "アンマー (anmā)" },
    { lang: "Yaghnobi (Iranian)", word: "mādar" },
    { lang: "Yakut (Turkic)", word: "ийэ (iye)" },
    { lang: "Yankunytjatjara", word: "Amma" },
    { lang: "Yanomami", word: "Amma" },
    { lang: "Yanyuwa", word: "Amma" },
    { lang: "Yapese", word: "ni" },
    { lang: "Yaqui", word: "Amma" },
    { lang: "Yauma (Bantu)", word: "mama" },
    { lang: "Yavapai", word: "Amma" },
    { lang: "Yazdi (Iranian)", word: "mādar" },
    { lang: "Yemenite Hebrew", word: "אֵם (em)" },
    { lang: "Yeni language", word: "Amma" },
    { lang: "Yevanic", word: "mana" },
    { lang: "Yi language", word: "a ma" },
    { lang: "Yiddish (Germanic)", word: "מאַמע (mame)" },
    { lang: "Yidgha (Iranian)", word: "mādar" },
    { lang: "Yokuts", word: "Amma" },
    { lang: "Yonaguni", word: "アンマー (anmā)" },
    { lang: "Yorùbá", word: "ìyá" },
    { lang: "Yucatec Maya", word: "na'" },
    { lang: "Yuchi", word: "Amma" },
    { lang: "Yukaghir", word: "eme" },
    { lang: "Yurats", word: "Amma" },
    { lang: "Yurok", word: "Amma" },

    // Z languages
    { lang: "Záparo", word: "Amma" },
    { lang: "Zapotec", word: "naa" },
    { lang: "Zazaki (Iranian)", word: "dayik" },
    { lang: "Zuni", word: "Amma" },
    { lang: "Zway / Zay (Semitic)", word: "em" },
    {lang: "braille",word:"⠁ ⠍ ⠍ ⠁"},
    {lang:"morse", word:".- -- -- .-"}


    
];

const container = document.getElementById("container");

data.forEach(item => {
    const div = document.createElement("div");
    div.className = "word";

    div.innerHTML = `
        ${item.word}
        <div class="tooltip">${item.lang}</div>
    `;

    container.appendChild(div);
});



